# Generated by Django 4.2.7 on 2023-11-04 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 18, 21, 46, 948404)),
        ),
    ]
