# Generated by Django 4.2.7 on 2023-11-05 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 10, 58, 35, 762077)),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('materias', models.ManyToManyField(to='materias.materia')),
            ],
        ),
    ]
